name: squirrel
description: "Accumulates structured log entries in a file-based local storage before sending them
              to the server."
version: 0.4.0
homepage: https://github.com/rtmigo/squirrel_dart

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  synchronized: ^3.0.0
  hive: ^2.0.4
  slugid: ^1.1.0

dev_dependencies:
  test: ^1.5.1
  lints: ^1.0.0


